# Numpy - Library to handle arrays.
- Statically typed (element types can't be mixed or altered)
- Non rresizeable (can't append or remove elements).
- Much faster than python's dynamically types lists.
- Support use of vector operations.
- A lot of other libraries is build from NumPy

## Create arrays

In [6]:
import numpy as np

my_array = np.array([5, 6, 7, 2], dtype=float) # Använd dtype om man vill hårdkoda datatypen
my_array.dtype

dtype('float64')

In [50]:
a2 = np.random.random(20)
a3 = np.random.randint(10, 20, 10)
a3

array([14, 12, 15, 12, 11, 11, 13, 14, 17, 12])

In [51]:
a4 = np.zeros(10)
a5 = np.ones(10)
a5


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
a6 = np.linspace(0, 10, 100)
a7 = np.arange(0, 10, 0.2)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

## Vectorized operations

In [52]:
x = [2, 4, 7, 1, 7, 3, 2, 5, 2]
x

[2, 4, 7, 1, 7, 3, 2, 5, 2]

In [53]:
y = [value * 2 for value in x]
y

[4, 8, 14, 2, 14, 6, 4, 10, 4]

In [54]:
x = np.array([2, 4, 7, 1, 7, 3, 2, 5, 2])
x

array([2, 4, 7, 1, 7, 3, 2, 5, 2])

In [55]:
import matplotlib.pyplot as plt

x = np.linspace(-10, 10, 100)
plt.plot(x, x**2)

ImportError: DLL load failed while importing _path: Det går inte att hitta den angivna modulen.

In [56]:
a = np.array([2, 4, 7, 1, ])
b = np.array([3, 2, 5, 2])

np.sqrt(a**2 + b**2)

array([3.60555128, 4.47213595, 8.60232527, 2.23606798])

In [57]:
b.shape

(4,)

## Array indexing and slicing
- Indexing and slicing works just as we are used to from python lists
- However, we can also use a list of indexes when indexing a numpy array
- Boolean masks/boolean indexing can be used to filter through data in array.

In [58]:
x = np.array([2, 4, 7, 1, 7, 3, 2, 5, 2])
x

array([2, 4, 7, 1, 7, 3, 2, 5, 2])

In [59]:
# Filtering using a list of indexes:
x[[0, 2, 0, -1, 1]]

array([2, 7, 2, 2, 4])

In [60]:
# Boolean indexing:
x[[False, False,  True, False,  True, False, False,  True, False]]

array([7, 7, 5])

In [61]:
# Boolean mask can be created when using comparison operators on numpy arrays
x >= 5

array([False, False,  True, False,  True, False, False,  True, False])

In [63]:
# Put thogether this looks like:
x[x >= 5]

array([7, 7, 5])

## Aggregation methods
An aggretions method is a method that takes a list/array of values by doing some calculations, returning a single value.


In [64]:
x = np.array([2, 4, 7, 1, 7, 3, 2, 5, 2])
x

array([2, 4, 7, 1, 7, 3, 2, 5, 2])

In [65]:
print(f"{x.sum() = }")
print(f"{x.min() = }")
print(f"{x.max() = }")
print(f"{x.mean() = }")

x.sum() = 33
x.min() = 1
x.max() = 7
x.mean() = 3.6666666666666665


## Multidimensional arrays

In [66]:
array_1d = np.array([2, 4, 7, 1, 7, 3, 2, 5, 2])
array_1d

array([2, 4, 7, 1, 7, 3, 2, 5, 2])

In [67]:
array_2d = np.array([[2, 4, 7, 1, 7], [3, 2, 5, 2, 6]])
array_2d

array([[2, 4, 7, 1, 7],
       [3, 2, 5, 2, 6]])

In [68]:
random_2d = np.random.randint(0, 10, [5, 4])
random_2d

array([[5, 6, 6, 5],
       [8, 2, 2, 3],
       [2, 1, 7, 7],
       [0, 7, 3, 0],
       [6, 6, 7, 8]])

In [69]:
random_3d = np.random.randint(0, 10, [2, 5, 4])
random_3d

array([[[3, 6, 6, 2],
        [8, 8, 7, 3],
        [4, 2, 6, 3],
        [3, 3, 3, 8],
        [7, 5, 5, 9]],

       [[2, 6, 8, 9],
        [6, 2, 9, 0],
        [3, 4, 1, 1],
        [8, 5, 0, 9],
        [5, 3, 4, 4]]])

## Slicing of 2D-arrays

In [70]:
random_2d

array([[5, 6, 6, 5],
       [8, 2, 2, 3],
       [2, 1, 7, 7],
       [0, 7, 3, 0],
       [6, 6, 7, 8]])

In [71]:
# Indexing in a 2d-array
random_2d[-1, 1]

6

In [73]:
# Slicing in a 2d array
random_2d[:3, 1:] = 0

In [74]:
random_2d

array([[5, 0, 0, 0],
       [8, 0, 0, 0],
       [2, 0, 0, 0],
       [0, 7, 3, 0],
       [6, 6, 7, 8]])